### PR TITLE
Fix relative request paths

### LINKED ISSUE #75: Calls to backend not working
location.host doesnt deliver the wanted address

### PR DESCRIPTION
**Pull request by hottek**
This hopefully resolves #75.  
It could be that this fix will not work because of the usage of the --base-href parameter in the build, but we'll have to see in the deployed version.  
If that is the case, we might have to revise the usage of that parameter. However, the usage of `lcoation.hostname` instead of `location.host` should only deliver the TLD as described [here](https://stackoverflow.com/a/11379802/12141469).

### CODE REVIEW

File: dashboard/src/app/services/custom-interceptor.ts [hunk 1]
```diff
@@ -9,9 +10,13 @@ export class CustomInterceptor implements HttpInterceptor {
   }
 
   intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
-    req = req.clone({
+    // console.log's for debugginggit add
```
Comment (hottek) [inline dashboard/src/app/services/custom-interceptor.ts:13]: got a typo there, remind me to fix that

File: dashboard/src/app/services/custom-interceptor.ts [hunk 2]
```diff
@@ -9,9 +10,13 @@ export class CustomInterceptor implements HttpInterceptor {
...
+    console.log(req);
+    const apiReq = req.clone({
+      url: `https://${environment.apiUrl}${req.url}`,
       withCredentials: true
     });
-    return next.handle(req);
+    console.log(apiReq);
```
Comment (zkdev) [inline dashboard/src/app/services/custom-interceptor.ts:19]: We should remove the console logs when it comes to finalization

Comment (hottek) [reply dashboard/src/app/services/custom-interceptor.ts:19]: sure
